/*
 * JS for Facebook_Me generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '35bcccf0-57b3-4a58-9dc9-6c60048bb7c8';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}];

function Facebook_Me_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'Name': 'Facebook_Me_Name',
        'mobilelist_4': 'Facebook_Me_mobilelist_4',
        'mobilelistitem_5': 'Facebook_Me_mobilelistitem_5',
        'mobilelistitembutton_6': 'Facebook_Me_mobilelistitembutton_6',
        'spacer_12': 'Facebook_Me_spacer_12',
        'backButtonList': 'Facebook_Me_backButtonList'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Facebook_Me_meService_onbeforesend_mapping_0"] = {
        "homeScreen": "Facebook_Me",
        "directions": [

        {
            "from_name": "access_token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "meService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "access_token": "{access_token}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['access_token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Facebook_Me_meService_onsuccess_mapping_0"] = {
        "homeScreen": "Facebook_Me",
        "directions": [

        {
            "from_name": "meService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Facebook_Me",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['first_name']",
                "target": "$['Name:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Facebook_Me_listPlaces_onbeforesend_mapping_0"] = {
        "homeScreen": "Facebook_Me",
        "directions": [

        {
            "from_name": "access_token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "listPlaces",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Facebook_Me_listPlaces_onsuccess_mapping_0"] = {
        "homeScreen": "Facebook_Me",
        "directions": [

        {
            "from_name": "listPlaces",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Facebook_Me",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]",
                "target": "$['mobilelistitem_5']"

            },

            {

                "source": "$['body'][i]['location']",
                "target": "$['mobilelistitem_5:text']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.meService = Apperyio.datasources.meService = new Apperyio.DataSource(Facebook_MeService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Facebook_Me_meService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Facebook_Me_meService_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.listPlaces = Apperyio.datasources.listPlaces = new Apperyio.DataSource(location_locations_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Facebook_Me_listPlaces_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Facebook_Me_listPlaces_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Facebook_Me';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Facebook_Me_onLoad = function() {
            Facebook_Me_elementsExtraJS();

            try {
                meService.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            Facebook_Me_deviceEvents();
            Facebook_Me_windowEvents();
            Facebook_Me_elementsEvents();
        };

    // screen window events


    function Facebook_Me_windowEvents() {

        $('#Facebook_Me').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#Facebook_Me').on({
            pageshow: function(event) {
                try {
                    listPlaces.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        });

    };

    // device events


    function Facebook_Me_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Facebook_Me_elementsExtraJS() {
        // screen (Facebook_Me) extra code

        /* mobilelist_4 */

        listView = $("#Facebook_Me_mobilelist_4");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Facebook_Me_mobilelist_4 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_5 */

    };

    // screen elements handler


    function Facebook_Me_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Facebook_Me_mobilecontainer2 [name="mobilelistitem_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["local"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('mobilelistitem_5', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('startScreen', {
                        reverse: false
                    });

                }
            },
        }, '#Facebook_Me_mobilecontainer2 [name="mobilelistitem_5"]');

        $(document).off("click", '#Facebook_Me_mobilecontainer2 [name="backButtonList"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        reverse: false
                    });

                }
            },
        }, '#Facebook_Me_mobilecontainer2 [name="backButtonList"]');

    };

    $(document).off("pagebeforeshow", "#Facebook_Me").on("pagebeforeshow", "#Facebook_Me", function(event, ui) {
        Apperyio.CurrentScreen = "Facebook_Me";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Facebook_Me_onLoad();
};

$(document).off("pagecreate", "#Facebook_Me").on("pagecreate", "#Facebook_Me", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Facebook_Me_js();
});