/*
 * JS for Facebook_Login generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '35bcccf0-57b3-4a58-9dc9-6c60048bb7c8';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}];

function Facebook_Login_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'loginButton': 'Facebook_Login_loginButton',
        'spacer_4': 'Facebook_Login_spacer_4',
        'signupButton': 'Facebook_Login_signupButton',
        'spacer_5': 'Facebook_Login_spacer_5',
        'mobilebutton1': 'Facebook_Login_mobilebutton1',
        'spacer_19': 'Facebook_Login_spacer_19',
        'mobilebuttonfb': 'Facebook_Login_mobilebuttonfb',
        'nameInput': 'Facebook_Login_nameInput',
        'lastnameInput': 'Facebook_Login_lastnameInput',
        'emailInput': 'Facebook_Login_emailInput',
        'usernameInput': 'Facebook_Login_usernameInput',
        'passwordInput': 'Facebook_Login_passwordInput',
        'spacer_16': 'Facebook_Login_spacer_16',
        'signupButtonSend': 'Facebook_Login_signupButtonSend',
        'spacer_12': 'Facebook_Login_spacer_12',
        'loginButtonSend': 'Facebook_Login_loginButtonSend',
        'spacer_18': 'Facebook_Login_spacer_18',
        'backButton': 'Facebook_Login_backButton'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Facebook_Login_GetInfo_onbeforesend_mapping_0"] = {
        "homeScreen": "Facebook_Login",
        "directions": [

        {
            "from_name": "facebook_token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "GetInfo",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "access_token": "{access_token}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['access_token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Facebook_Login_GetInfo_onsuccess_mapping_0"] = {
        "homeScreen": "Facebook_Login",
        "directions": [

        {
            "from_name": "GetInfo",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Facebook_Login",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['last_name']",
                "target": "$['lastnameInput:text']"

            },

            {

                "source": "$['body']['first_name']",
                "target": "$['nameInput:text']"

            },

            {

                "source": "$['body']['email']",
                "target": "$['emailInput:text']"

            },

            {

                "source": "$['body']['first_name']",
                "target": "$['usernameInput:text']"

            },

            {

                "source": "$['body']['last_name']",
                "target": "$['passwordInput:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Facebook_Login_loginService_onbeforesend_mapping_0"] = {
        "homeScreen": "Facebook_Login",
        "directions": [

        {
            "from_name": "Facebook_Login",
            "from_type": "UI",

            "to_name": "loginService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['usernameInput:text']",
                "target": "$['parameters']['username']"

            },

            {

                "source": "$['passwordInput:text']",
                "target": "$['parameters']['password']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Facebook_Login_loginService_onsuccess_mapping_0"] = {
        "homeScreen": "Facebook_Login",
        "directions": [

        {
            "from_name": "loginService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "access_token",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['sessionToken']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Facebook_Login_signupService_onbeforesend_mapping_0"] = {
        "homeScreen": "Facebook_Login",
        "directions": [

        {
            "from_name": "Facebook_Login",
            "from_type": "UI",

            "to_name": "signupService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['emailInput:text']",
                "target": "$['body']['email']"

            },

            {

                "source": "$['lastnameInput:text']",
                "target": "$['body']['lastName']"

            },

            {

                "source": "$['nameInput:text']",
                "target": "$['body']['name']"

            },

            {

                "source": "$['usernameInput:text']",
                "target": "$['body']['username']"

            },

            {

                "source": "$['passwordInput:text']",
                "target": "$['body']['password']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Facebook_Login_signupService_onsuccess_mapping_0"] = {
        "homeScreen": "Facebook_Login",
        "directions": [

        {
            "from_name": "signupService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "access_token",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['sessionToken']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Facebook_Login_Atual_onbeforesend_mapping_0"] = {
        "homeScreen": "Facebook_Login",
        "directions": [

        {

            "to_name": "Atual",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "maximumAge": 3000,
                        "timeout": 5000,
                        "enableHighAccuracy": true,
                        "watchPosition": false
                    }
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["Facebook_Login_Atual_onsuccess_mapping_0"] = {
        "homeScreen": "Facebook_Login",
        "directions": []
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.GetInfo = Apperyio.datasources.GetInfo = new Apperyio.DataSource(Facebook_MeService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Facebook_Login_GetInfo_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Facebook_Login_GetInfo_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.loginService = Apperyio.datasources.loginService = new Apperyio.DataSource(location_login_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Facebook_Login_loginService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Facebook_Login_loginService_onsuccess_mapping_0"]);
            Apperyio.navigateTo('startScreen', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert("Username or Password invalid");
        }
    });

    window.signupService = Apperyio.datasources.signupService = new Apperyio.DataSource(location_signup_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Facebook_Login_signupService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Facebook_Login_signupService_onsuccess_mapping_0"]);
            Apperyio.navigateTo('startScreen', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            var response = JSON.parse(jqXHR.responseText);
            alert(response.description);
        }
    });

    window.Atual = Apperyio.datasources.Atual = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Facebook_Login_Atual_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Facebook_Login_Atual_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Facebook_Login';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Facebook_Login_onLoad = function() {
            Facebook_Login_elementsExtraJS();

            Facebook_Login_deviceEvents();
            Facebook_Login_windowEvents();
            Facebook_Login_elementsEvents();
        };

    // screen window events


    function Facebook_Login_windowEvents() {

        $('#Facebook_Login').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Facebook_Login_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Facebook_Login_elementsExtraJS() {
        // screen (Facebook_Login) extra code

    };

    // screen elements handler


    function Facebook_Login_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Facebook_Login_mobilecontainer1 [name="loginButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio("loginButton").hide();
                    Apperyio("signupButton").hide();
                    Apperyio("mobilebutton1").hide();
                    Apperyio("mobilebuttonfb").hide();
                    Apperyio("spacer_4").hide();
                    Apperyio("spacer_5").hide();
                    Apperyio("usernameInput").show();
                    Apperyio("passwordInput").show();
                    Apperyio("loginButtonSend").show();
                    Apperyio("spacer_16").show();
                    Apperyio("backButton").show();
                    Apperyio("spacer_18").show();

                }
            },
        }, '#Facebook_Login_mobilecontainer1 [name="loginButton"]');

        $(document).off("click", '#Facebook_Login_mobilecontainer1 [name="signupButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio("loginButton").hide();
                    Apperyio("signupButton").hide();
                    Apperyio("mobilebutton1").hide();
                    Apperyio("mobilebuttonfb").hide();
                    Apperyio("spacer_4").hide();
                    Apperyio("spacer_5").hide();
                    Apperyio("nameInput").show();
                    Apperyio("lastnameInput").show();
                    //Apperyio("emailInput").show();
                    Apperyio("usernameInput").show();
                    Apperyio("passwordInput").show();
                    Apperyio("signupButtonSend").show();
                    Apperyio("spacer_16").show();
                    Apperyio("backButton").show();
                    Apperyio("spacer_18").show();

                }
            },
        }, '#Facebook_Login_mobilecontainer1 [name="signupButton"]');

        $(document).off("click", '#Facebook_Login_mobilecontainer1 [name="mobilebutton1"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Helper.init();;
                    try {
                        GetInfo.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    try {
                        loginService.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Facebook_Login_mobilecontainer1 [name="mobilebutton1"]');

        $(document).off("click", '#Facebook_Login_mobilecontainer1 [name="mobilebuttonfb"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Helper.init();
                    try {
                        GetInfo.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    try {
                        signupService.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Facebook_Login_mobilecontainer1 [name="mobilebuttonfb"]');

        $(document).off("click", '#Facebook_Login_mobilecontainer1 [name="signupButtonSend"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        signupService.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Facebook_Login_mobilecontainer1 [name="signupButtonSend"]');

        $(document).off("click", '#Facebook_Login_mobilecontainer1 [name="loginButtonSend"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        loginService.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    Apperyio("usernameInput").val("");
                    Apperyio("passwordInput").val("");

                }
            },
        }, '#Facebook_Login_mobilecontainer1 [name="loginButtonSend"]');

        $(document).off("click", '#Facebook_Login_mobilecontainer1 [name="backButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    location.reload();

                }
            },
        }, '#Facebook_Login_mobilecontainer1 [name="backButton"]');

    };

    $(document).off("pagebeforeshow", "#Facebook_Login").on("pagebeforeshow", "#Facebook_Login", function(event, ui) {
        Apperyio.CurrentScreen = "Facebook_Login";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Facebook_Login_onLoad();
};

$(document).off("pagecreate", "#Facebook_Login").on("pagecreate", "#Facebook_Login", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Facebook_Login_js();
});