/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '35bcccf0-57b3-4a58-9dc9-6c60048bb7c8';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}];

function startScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_4': 'startScreen_mobilenavbar_4',
        'pinpointmeItem': 'startScreen_pinpointmeItem',
        'myplacesItem': 'startScreen_myplacesItem',
        'signoutItem': 'startScreen_signoutItem',
        'google_map': 'startScreen_google_map',
        'marker_3': 'startScreen_marker_3',
        'to': 'startScreen_to',
        'show_directions': 'startScreen_show_directions',
        'marker_location': 'startScreen_marker_location',
        'place_marker': 'startScreen_place_marker',
        'show_traffic': 'startScreen_show_traffic',
        'get_markers': 'startScreen_get_markers',
        'show_my_location': 'startScreen_show_my_location'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["startScreen_show_directions_onclick_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "local",
            "from_type": "LOCAL_STORAGE",

            "to_name": "startScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$",
                "target": "$['to:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_convert_address_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "startScreen",
            "from_type": "UI",

            "to_name": "convert_address",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "address": "City of Salvador",
                    "sensor": "false"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['marker_location:text']",
                "target": "$['parameters']['address']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_convert_address_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "convert_address",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "markerLat",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['results'][0]['geometry']['location']['lat']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "convert_address",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "markerLng",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['results'][0]['geometry']['location']['lng']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_get_db_locations_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "access_token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "get_db_locations",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_geolocation1_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {

            "to_name": "geolocation1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "maximumAge": 3000,
                        "timeout": 5000,
                        "enableHighAccuracy": true,
                        "watchPosition": false
                    }
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["startScreen_geolocation1_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "geolocation1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "currentLat",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['data']['coords']['latitude']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "geolocation1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "currentLng",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['data']['coords']['longitude']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_listService_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "access_token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "listService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_listService_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": []
    };

    Apperyio.mappings["startScreen_logoutService_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "access_token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "logoutService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_add_db_Marker_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "access_token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "add_db_Marker",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        },

        {
            "from_name": "here",
            "from_type": "LOCAL_STORAGE",

            "to_name": "add_db_Marker",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['location']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.convert_address = Apperyio.datasources.convert_address = new Apperyio.DataSource(ConvertAddress, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_convert_address_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_convert_address_onsuccess_mapping_0"]);
            var markerLatLng = new google.maps.LatLng(localStorage.getItem('markerLat'), localStorage.getItem('markerLng'));

            var marker = new google.maps.Marker({
                position: markerLatLng,
                map: map,
                title: data.results[0].address_components[0].long_name,
                animation: google.maps.Animation.DROP
            });

            bounds.extend(markerLatLng);
            map.fitBounds(bounds);;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.get_db_locations = Apperyio.datasources.get_db_locations = new Apperyio.DataSource(location_locations_read_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_get_db_locations_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            for (var i = 0; i < data.length; i++) {
                convert_address.execute({
                    'data': {
                        'address': data[i].location,
                        'sensor': false
                    }
                });
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.geolocation1 = Apperyio.datasources.geolocation1 = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_geolocation1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_geolocation1_onsuccess_mapping_0"]);
            var markerLatLng = new google.maps.LatLng(Apperyio.storage.currentLat.get(), Apperyio.storage.currentLng.get());

            var marker = new google.maps.Marker({
                position: markerLatLng,
                map: map,
                icon: 'http://i.imgur.com/fDUI8bZ.png'
            });

            map.setCenter(markerLatLng);
            map.setZoom(15);;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.listService = Apperyio.datasources.listService = new Apperyio.DataSource(location_locations_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_listService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_listService_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.logoutService = Apperyio.datasources.logoutService = new Apperyio.DataSource(location_logout_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_logoutService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.navigateTo('Facebook_Login', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.add_db_Marker = Apperyio.datasources.add_db_Marker = new Apperyio.DataSource(location_locations_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_add_db_Marker_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {},
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            initialize();

            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events


    function startScreen_windowEvents() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#startScreen').on({
            pageshow: function(event) {
                try {
                    geolocation1.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        });

    };

    // device events


    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code

        /* google_map */

        $("[name = 'google_map']").wrap("<div/>");
        $("[name = 'google_map']").parent().css("margin-left", $("[name = 'google_map']").css("margin-left"));
        $("[name = 'google_map']").parent().css("margin-right", $("[name = 'google_map']").css("margin-right"));
        $("[name = 'google_map']").css("margin-left", '0');
        $("[name = 'google_map']").css("margin-right", '0');

        var google_map_options = {
            markerSourceName: "google_map_markers",
            latitude: "",
            longitude: "",
            address: "",
            zoom: 2,
            showLocationMarker: false
        }

        Apperyio.__registerComponent('google_map', new Apperyio.ApperyMapComponent("google_map", google_map_options));
        $("[name='google_map_markers'] [apperytype='marker']").attr("reRender", "google_map");
        $(":mobile-pagecontainer").off("pagecontainershow.startScreen_mobilecontainer1").on("pagecontainershow.startScreen_mobilecontainer1", function(event, ui) {
            if (($('#startScreen_google_map', ui.toPage).length > 0) && (Apperyio('google_map') != undefined)) {
                Apperyio('google_map').refresh();
            }
        });

    };

    // screen elements handler


    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#startScreen_mobileheader1 [name="pinpointmeItem"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        geolocation1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#startScreen_mobileheader1 [name="pinpointmeItem"]');
        $(document).off("click", '#startScreen_mobileheader1 [name="myplacesItem"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Facebook_Me', {
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobileheader1 [name="myplacesItem"]');
        $(document).off("click", '#startScreen_mobileheader1 [name="signoutItem"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        logoutService.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#startScreen_mobileheader1 [name="signoutItem"]');

        $(document).off("click", '#startScreen_mobilecontainer1 [name="show_directions"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.processMappingAction(Apperyio.mappings["startScreen_show_directions_onclick_mapping_0"]);
                    var destinationAddress = Apperyio("to").val();
                    displayDirections(localStorage.getItem('local'), map);

                }
            },
        }, '#startScreen_mobilecontainer1 [name="show_directions"]');

        $(document).off("click", '#startScreen_mobilecontainer1 [name="place_marker"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        geolocation1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    var stringHere = localStorage.getItem('currentLat') + "," + localStorage.getItem('currentLng');
                    localStorage.setItem('here', stringHere);

                    //alert(localStorage.getItem('here'));

/*google.maps.event.addListener(Apperyio('place_marker'), 'click', function(event) {
    var myLatLng = event.latLng;
    var lat = myLatLng.lat();
    var lng = myLatLng.lng();
});
Apperyio('marker_location').val(myLatLng);

//Apperyio('marker_location').val(localStorage.getItem(currentLat)+","+localStorage.getItem(currentLng));*/

                    //alert(localStorage.getItem('currentLat')+","+localStorage.getItem('currentLng'));

/*
Puts the markers on the map


var locations = new Array();
locations = Apperyio('marker_location').val().split(",");

for (var i=0;i<locations.length;i++)
{
    convert_address.execute({
        'data' : {
            'address' : locations[i],
            'sensor' : false
        }
    });
}*/

                    ;
                    try {
                        add_db_Marker.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#startScreen_mobilecontainer1 [name="place_marker"]');
        $(document).off("click", '#startScreen_mobilecontainer1 [name="show_traffic"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var trafficLayer = new google.maps.TrafficLayer();
                    trafficLayer.setMap(map);

                }
            },
        }, '#startScreen_mobilecontainer1 [name="show_traffic"]');
        $(document).off("click", '#startScreen_mobilecontainer1 [name="get_markers"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        get_db_locations.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
/*var locations = new Array();
locations = Apperyio('marker_location').val().split(",");

for (var i=0;i<locations.length;i++)
{
    convert_address.execute({
        'data' : {
            'address' : locations[i],
            'sensor' : false
        }
    });
}*/
                    ;

                }
            },
        }, '#startScreen_mobilecontainer1 [name="get_markers"]');
        $(document).off("click", '#startScreen_mobilecontainer1 [name="show_my_location"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        geolocation1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#startScreen_mobilecontainer1 [name="show_my_location"]');

    };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    startScreen_onLoad();
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});